### ISSUE TITLE
Не клонируется репозиторий

### ISSUE THREAD

**Issue by DimaKropachev** [jKakZyo/go_webcalc#2]
Пытаюсь склонировать репозиторий командой указанной в README: `git clone https://github.com/jKakZyo/go_webcalc.git`
Выдает ошибку:
`error: invalid path 'cmd /calc_service'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'`

**Comment by jKakZyo** [comment]
Попробуйте еще раз прочитать ридми файл
